### ISSUE TITLE
[Client] Figure out what (if any) React Design System to use

### ISSUE THREAD

**Issue by Tyresius92** [Tyresius92/le-chat#1]
I have reasonably extensive experience with Material UI, and wouldn't mind doing another project using that library: https://material-ui.com/#/

Here is a list of possible alternatives: https://github.com/jbranchaud/awesome-react-design-systems

Explore potential alternatives and make a recommendation on which design system seems the coolest/easiest to use/whatever else seems important.

**Comment by Tyresius92** [comment]
Biggest hesitation with Material UI is that I dont know that I'm in love with their built in styling/theming solution.

**Comment by marcgaj** [comment]
[Atomize](https://atomizecode.com/docs/react/atoms) looks good if we want something bare bones and customizable

[Chakra](https://chakra-ui.com/) looks neat and has a few really useful components already baked in like Avatars, Skeleton (loading shimmer/placeholder), Spinners, Drawer, Modal, Dialogs/Alerts, and a few custom hooks

**Comment by Tyresius92** [comment]
Chakra does look pretty neat! I'm gonna play with it a little bit, but it looks to be a bit more mature than Atomize, and has a variety of cool stuff already built out. 

Also, huge plus: they've made sure that accessibility is taken care of. I might be leaning that way. @benjimorr tagging you just to see if you want to weigh in on this one.

**Comment by benjimorr** [comment]
Talked with Tyrel offline today, and I think Chakra would be my pick (although I like the look of the UI elements from Atomize). I like how built out Chakra is and although the documentation may be lacking in some areas, I think we should be able to figure out how their components work.

**Comment by Tyresius92** [comment]
Cool! Let's use Chakra then. Closing this issue out. Adding another one (to the Trello Board!) for implementation.
