### ISSUE TITLE
Determine if we want to use the All Contributors bot or some alternative

### ISSUE THREAD

**Issue by Tyresius92** [Tyresius92/le-chat#15]
Having a streamlined way to update the README when a new person contributes to the project will make it easier to update our docs and keep all of our acknowledgements up to date. 

Determine if we should use All Contributors or some other option.

https://allcontributors.org/

**Comment by marcgaj** [comment]
![image](https://user-images.githubusercontent.com/15946968/84599100-8d97df00-ae3d-11ea-93c0-557dd4e2c884.png)

**Comment by marcgaj** [comment]
![rustled](https://user-images.githubusercontent.com/15946968/84599195-42ca9700-ae3e-11ea-8805-9cc79aa8da23.gif)
