### ISSUE TITLE
Set up sentry

### ISSUE THREAD

**Issue by Tyresius92** [Tyresius92/le-chat#25]
Follow on from #16 

Set up a logger directory in both client and server directories to send data to Sentry

**Comment by Tyresius92** [comment]
Regardless of the Sentry API, our API should consist of only `info`, `warn`, and `error` methods. 

Logger usage should look like 
```
import logger from 'path/to/logger';

logger.info('My informational message');
logger.warn('My warning message');
logger.error('THE WORLD IS ON FIRE');
```

For client side logging, these may need to be routed through our server to prevent API keys from being included in the build.

**Comment by marcgaj** [comment]
What happens if the server goes down? How would logs persist?

I'm cutting a PR to add a Sentry integration to the client, we can check that out

**Comment by Tyresius92** [comment]
Will look over the  I'm mainly thinking of how CRA embeds environment variables in the build - so if there's a secret that needs to be passed along with our logs there's not a way to keep the secret...secret...

**Comment by Tyresius92** [comment]
@marcgaj any progress on a server side logger? I can replicate the client side one, but don't want to duplicate work if you just haven't pushed it or something

**Comment by marcgaj** [comment]
No, I haven't touched that part of it.

**Comment by marcgaj** [comment]
![image](https://user-images.githubusercontent.com/15946968/84582245-a5c51b00-adb7-11ea-91c6-f8f3e04ff272.png)
