### ISSUE TITLE
Find a logo

### ISSUE THREAD

**Issue by Tyresius92** [Tyresius92/le-chat#4]
In keeping with our cat/chat pun, we should TOTALLY have a cat as our logo/icon thing. Find or design or draw a cat to use as our logo.

**Comment by marcgaj** [comment]
![le_chat_mock](https://user-images.githubusercontent.com/15946968/83975275-11dbe680-a8c1-11ea-80c2-bf664ddb0057.png)

**Comment by Tyresius92** [comment]
Yeah sounds good. Can you cut a PR to add the jpeg/png/whatever format seems appropriate to `client/src/images` or `client/src/assets` or something that seems reasonable?

**Comment by marcgaj** [comment]
Going for more of a vector style, what about 
![image](https://user-images.githubusercontent.com/15946968/84569293-64028900-ad53-11ea-8f64-b4e5d242d848.png)

**Comment by marcgaj** [comment]
little too rounded for a cat but as a draft^

**Comment by marcgaj** [comment]
![image](https://user-images.githubusercontent.com/15946968/84569347-c52a5c80-ad53-11ea-8e71-da6aa61eceab.png)

**Comment by Tyresius92** [comment]
Yaaaaaassssss

**Comment by marcgaj** [comment]
cool, I have full vector-ish source so can scale and clean up as needed. totally orig so no risk
