### ISSUE TITLE
create a Le Chat specific Button component

### ISSUE THREAD

**Issue by Tyresius92** [Tyresius92/le-chat#50]
Implement a Le Chat specific button component that uses an underlying Chakra button, but which, when imported, comes in already styled/themed as we want it to be.

**Comment by marcgaj** [comment]
Just to clarify the intent, is this more to get a pretty button or kick off the custom theme?

**Comment by Tyresius92** [comment]
A little of both, but the main thing is to have the `Le Chat` style button in a single place so if we ever decide to move away from Chakra, we're not updating imports in a billion places. Idea being that if i need a button, I _always_ do `import Button from 'LeChatButton'` instead of importing from Chakra directly
