### ISSUE TITLE
Create a custom theme

### ISSUE THREAD

**Issue by Tyresius92** [Tyresius92/le-chat#53]
Implement a custom theme, and provide it to the ThemeProvider at the root of the DOM. 

Use Paletton to create a custom color scheme, and set up some basic defaults in the theme.

**Comment by Tyresius92** [comment]
Woops. Apparently I had the ability to push to master. 

Pretty sure I've blocked that now, but I already pushed up a theme. You can see the colors here: https://coolors.co/41d3bd-9c2625-343434 

There's also an example usage in the SignOutButton.js

**Comment by marcgaj** [comment]
Should we close this?

**Comment by marcgaj** [comment]
I think this theme might get confusing depending on how these colors nest - red buttons in particular have _connotations_ so I'm curious if you had some color specific layouts in mind

**Comment by Tyresius92** [comment]
I'm thinking the turquoise for almost _everything_ because it pairs nicely with the current logo. 

Most action buttons (cancel, undo, etc.) will be some variant of the gray. 

The only buttons that will be red will be actual danger buttons - Delete account, things like that.

**Comment by Tyresius92** [comment]
If/when we swap in a new logo, I'm more than happy to revisit all of these color choices.

**Comment by marcgaj** [comment]
Might be nice to work in one more neutral/accent color - I’m conflicted on
where to use the red but feel obliged to since its in the core set of
custom colors (and the cats attire). We could tweak the logo colors if we
want something instead of red

**Comment by Tyresius92** [comment]
@marcgaj Yeah feel free to modify however you like! I'm in no way attached to these colors, and personally I find the whole color thing to be a bit overwhelming, so perfectly happy to let someone else take point on this.

I do really like the coolors tool. If you go into it, you can lock any of the colors, and then press the space bar to get new stuff that should go reasonably well. 

A few options that came up for me (again, not attached to any of these - feel free to pick your own stuff)

https://coolors.co/41d3bd-9c2625-343434-d5b942
https://coolors.co/41d3bd-9c2625-343434-cea07e
https://coolors.co/41d3bd-9c2625-343434-ffe787
https://coolors.co/41d3bd-9c2625-343434-7d5ba6

And then eliminating the turquoise:

https://coolors.co/9c2625-343434-3f7d20-3f88c5 (I actually quite like this one)
https://coolors.co/9c2625-343434-e7e247-5c80bc
https://coolors.co/9c2625-343434-ffffff-639fab
https://coolors.co/9c2625-343434-ffc857-519872

And finally, eliminating the red: 

https://coolors.co/41d3bd-343434-4f772d-8789c0
https://coolors.co/343434-ffffff-dd7230-4c956c

**Comment by Tyresius92** [comment]
@benjimorr and I decided on this one: 

https://coolors.co/41d3bd-343434-4f772d-8789c0
