### ISSUE TITLE
[Bug] Colors in script fail

### ISSUE THREAD

**Issue by marcgaj** [Tyresius92/le-chat#56]
Getting raw output on Windows

```
> client@0.1.0 smellsGood C:\code\le-chat\client
> echo "\x1b[92mGreat success!! Your client-side code smells goooood!\x1b[0m"

"\x1b[92mGreat success!! Your client-side code smells goooood!\x1b[0m"
```

**Comment by Tyresius92** [comment]
Boooooo windows. Yeah i thought that might be an issue but was hoping no one was coding on a windows computer :P 

It's cool though, there are instructions here to make it work cross platform: https://stackoverflow.com/questions/50226385/apply-visual-styling-to-echo-commands-used-in-npm-scripts-via-package-json 

I'll cut a PR later today to fix it.
