### ISSUE TITLE
Set up a Trello board

### ISSUE THREAD

**Issue by Tyresius92** [Tyresius92/le-chat#7]
Trello boards are good for organization, right? Set up a trello board, and add it to the README. 

Blocked by #2 due to the fact that we don't _really_ have a README yet...

**Comment by Tyresius92** [comment]
I have written a proper README. Now that that's done, we can create a Trello Board and link it in whatever the most reasonable section is.

**Comment by marcgaj** [comment]
https://trello.com/b/VtxxQngU/le-chat-app
